openapi: 3.0.0
components:
    schemas:
        GetAllPets:
            type: object
            properties:
                pets:
                    type: array
                    format: array
                    description: Returns list of pets
                    items:
                        $ref: '#/components/schemas/pet'
                platform:
                    type: string
        category:
            type: object
            description: Type of pet
            properties:
                id:
                    type: number
                    format: int
                    description: Pet ID
                    default: "1"
                    example: "1"
                name:
                    type: string
                    description: Category name for the pets
                    enum:
                        - cat dog
                    default: cat
                    example: dog
        pet:
            type: object
            properties:
                category:
                    type: object
                    description: Type of pet
                    properties:
                        id:
                            type: number
                            format: int
                            description: Pet ID
                            default: "1"
                            example: "1"
                        name:
                            type: string
                            description: Category name for the pets
                            enum:
                                - cat dog
                            default: cat
                            example: dog
                name:
                    type: string
                    format: text
                    description: Name of the pet
                    default: tommy
                    example: rambo
info:
    title: Sample Spec - OpenAPI 3.1
    description: Sample description.
    version: 3.1.0
paths:
    /pets/:
        get:
            tags:
                - pets
            summary: Fetches pet
            description: Fetches all pet
            operationId: getPet
            parameters:
                - name: x-agent-id
                  in: header
                  description: Agent ID for the request
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json: {}
            responses:
                "200":
                    description: Response for GetPetByID API
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    pets:
                                        type: array
                                        format: array
                                        description: Returns list of pets
                                        items:
                                            $ref: '#/components/schemas/pet'
                                    platform:
                                        type: string
                "400":
                    description: Error
                    content:
                        application/json: {}
servers:
    - url: http://localhost:8080
