openapi: 3.0.0
components:
    schemas:
        ErrorResponse:
            type: object
            properties:
                message:
                    type: string
        SampleRequest1:
            type: object
            properties:
                field3:
                    type: string
        SampleRequest2:
            type: object
            properties:
                field5:
                    type: string
                field6:
                    type: integer
                    format: int
                sample_response_1:
                    $ref: '#/components/schemas/SampleResponse1'
        SampleResponse1:
            type: object
            properties:
                field4:
                    type: string
        SampleResponse2:
            type: object
            properties:
                field2:
                    type: string
info:
    title: My API
    version: 1.0.0
paths: {}
servers:
    - url: http://localhost:8080
